# -*- mode: python -*-

block_cipher = None


a = Analysis(['SpawnCycler.py'],
             pathex=['C:\\SpawnCycler\\trunk\src\\'],
             binaries=[],
             datas=[],
             hiddenimports=[],
             hookspath=[],
             runtime_hooks=[],
             excludes=[],
             win_no_prefer_redirects=False,
             win_private_assemblies=False,
             cipher=block_cipher)


a.datas += [('img\\icon_abomination.png', 'C:\\SpawnCycler\\trunk\src\\img\\icon_abomination.png', "DATA"),
            ('img\\icon_abomspawn.png', 'C:\\SpawnCycler\\trunk\src\\img\\icon_abomspawn.png', "DATA"),
            ('img\\icon_about.png', 'C:\\SpawnCycler\\trunk\src\\img\\icon_about.png', "DATA"),
            ('img\\icon_add.png', 'C:\\SpawnCycler\\trunk\src\\img\\icon_add.png', "DATA"),
            ('img\\icon_alphaclot.png', 'C:\\SpawnCycler\\trunk\src\\img\\icon_alphaclot.png', "DATA"),
            ('img\\icon_alphafleshpound.png', 'C:\\SpawnCycler\\trunk\src\\img\\icon_alphafleshpound.png', "DATA"),
            ('img\\icon_alphascrake.png', 'C:\\SpawnCycler\\trunk\src\\img\\icon_alphascrake.png', "DATA"),
            ('img\\icon_analyze.png', 'C:\\SpawnCycler\\trunk\src\\img\\icon_analyze.png', "DATA"),
            ('img\\icon_batch.png', 'C:\\SpawnCycler\\trunk\src\\img\\icon_batch.png', "DATA"),
            ('img\\icon_bloat.png', 'C:\\SpawnCycler\\trunk\src\\img\\icon_bloat.png', "DATA"),
            ('img\\icon_check.png', 'C:\\SpawnCycler\\trunk\src\\img\\icon_check.png', "DATA"),
            ('img\\icon_crawler.png', 'C:\\SpawnCycler\\trunk\src\\img\\icon_crawler.png', "DATA"),
            ('img\\icon_cyst.png', 'C:\\SpawnCycler\\trunk\src\\img\\icon_cyst.png', "DATA"),
            ('img\\icon_delete.png', 'C:\\SpawnCycler\\trunk\src\\img\\icon_delete.png', "DATA"),
            ('img\\icon_edar.png', 'C:\\SpawnCycler\\trunk\src\\img\\icon_edar.png', "DATA"),
            ('img\\icon_edar_emp.png', 'C:\\SpawnCycler\\trunk\src\\img\\icon_edar_emp.png', "DATA"),
            ('img\\icon_edar_laser.png', 'C:\\SpawnCycler\\trunk\src\\img\\icon_edar_laser.png', "DATA"),
            ('img\\icon_edar_rocket.png', 'C:\\SpawnCycler\\trunk\src\\img\\icon_edar_rocket.png', "DATA"),
            ('img\\icon_elitecrawler.png', 'C:\\SpawnCycler\\trunk\src\\img\\icon_elitecrawler.png', "DATA"),
            ('img\\icon_fleshpound.png', 'C:\\SpawnCycler\\trunk\src\\img\\icon_fleshpound.png', "DATA"),
            ('img\\icon_generate.png', 'C:\\SpawnCycler\\trunk\src\\img\\icon_generate.png', "DATA"),
            ('img\\icon_go.png', 'C:\\SpawnCycler\\trunk\src\\img\\icon_go.png', "DATA"),
            ('img\\icon_gorefast.png', 'C:\\SpawnCycler\\trunk\src\\img\\icon_gorefast.png', "DATA"),
            ('img\\icon_gorefiend.png', 'C:\\SpawnCycler\\trunk\src\\img\\icon_gorefiend.png', "DATA"),
            ('img\\icon_hans.png', 'C:\\SpawnCycler\\trunk\src\\img\\icon_hans.png', "DATA"),
            ('img\\icon_husk.png', 'C:\\SpawnCycler\\trunk\src\\img\\icon_husk.png', "DATA"),
            ('img\\icon_kingfleshpound.png', 'C:\\SpawnCycler\\trunk\src\\img\\icon_kingfleshpound.png', "DATA"),
            ('img\\icon_matriarch.png', 'C:\\SpawnCycler\\trunk\src\\img\\icon_matriarch.png', "DATA"),
            ('img\\icon_open.png', 'C:\\SpawnCycler\\trunk\src\\img\\icon_open.png', "DATA"),
            ('img\\icon_patriarch.png', 'C:\\SpawnCycler\\trunk\src\\img\\icon_patriarch.png', "DATA"),
            ('img\\icon_presets.png', 'C:\\SpawnCycler\\trunk\src\\img\\icon_presets.png', "DATA"),
            ('img\\icon_quarterpound.png', 'C:\\SpawnCycler\\trunk\src\\img\\icon_quarterpound.png', "DATA"),
            ('img\\icon_rioter.png', 'C:\\SpawnCycler\\trunk\src\\img\\icon_rioter.png', "DATA"),
            ('img\\icon_save.png', 'C:\\SpawnCycler\\trunk\src\\img\\icon_save.png', "DATA"),
            ('img\\icon_saveas.png', 'C:\\SpawnCycler\\trunk\src\\img\\icon_saveas.png', "DATA"),
            ('img\\icon_scrake.png', 'C:\\SpawnCycler\\trunk\src\\img\\icon_scrake.png', "DATA"),
            ('img\\icon_shiftdown.png', 'C:\\SpawnCycler\\trunk\src\\img\\icon_shiftdown.png', "DATA"),
            ('img\\icon_shiftdown_off.png', 'C:\\SpawnCycler\\trunk\src\\img\\icon_shiftdown_off.png', "DATA"),
            ('img\\icon_shiftup.png', 'C:\\SpawnCycler\\trunk\src\\img\\icon_shiftup.png', "DATA"),
            ('img\\icon_shiftup_off.png', 'C:\\SpawnCycler\\trunk\src\\img\\icon_shiftup_off.png', "DATA"),
            ('img\\icon_siren.png', 'C:\\SpawnCycler\\trunk\src\\img\\icon_siren.png', "DATA"),
            ('img\\icon_slasher.png', 'C:\\SpawnCycler\\trunk\src\\img\\icon_slasher.png', "DATA"),
            ('img\\icon_stalker.png', 'C:\\SpawnCycler\\trunk\src\\img\\icon_stalker.png', "DATA"),
            ('img\\icon_switch.png', 'C:\\SpawnCycler\\trunk\src\\img\\icon_switch.png', "DATA"),
            ('img\\icon_warning.png', 'C:\\SpawnCycler\\trunk\src\\img\\icon_warning.png', "DATA"),
            ('img\\logo.png', 'C:\\SpawnCycler\\trunk\src\\img\\logo.png', "DATA")]


pyz = PYZ(a.pure, a.zipped_data,
             cipher=block_cipher)


exe = EXE(pyz,
          a.scripts,
          a.binaries,
          a.zipfiles,
          a.datas,
          name='SpawnCycler',
          debug=False,
          strip=False,
          upx=True,
          console=False,
          icon='C:\\SpawnCycler\\trunk\src\\spawncycler.ico')
